# SPDX-FileCopyrightText: 2021 GNOME Foundation
#
# SPDX-License-Identifier: CC0-1.0

[library]
name = "gdk-pixbuf"
browse_url = "https://gitlab.gnome.org/GNOME/gdk-pixbuf/"
repository_url = "https://gitlab.gnome.org/GNOME/gdk-pixbuf.git"
website_url = "https://www.gtk.org"
authors = "GTK Development Team"
logo_url = "https://www.gtk.org/"
license = "GPL-2.1-or-later"
description = "Image loading library"
dependencies = [ "gobject", "gio" ]

  [dependencies.gobject]
  name = "GObject"
  description = "The base type system library"
  docs_url = "https://developer.gnome.org/gobject/stable"

  [dependencies.gio]
  name = "GIO"
  description = "GObject Interfaces and Object"
  docs_url = "https://developer.gnome.org/gio/stable"

[theme]
name = "basic"

[source-location]
base_url = "https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/blob/master/"
