# SPDX-FileCopyrightText: 2021 GNOME Foundation
#
# SPDX-License-Identifier: CC0-1.0

[library]
namespace = "Gtk"
version = "3.0"
browse_url = "https://gitlab.gnome.org/GNOME/gtk/"
repository_url = "https://gitlab.gnome.org/GNOME/gtk.git"
website_url = "https://www.gtk.org"
authors = "GTK Development Team"
logo_url = "https://www.gtk.org/"
license = "GPL-2.1-or-later"
description = "The GTK toolkit"
dependencies = [ "GObject-2.0", "Graphene-1.0", "Pango-1.0", "Gdk-3.0" ]

  [dependencies."GObject-2.0"]
  name = "GObject"
  description = "The base type system library"
  docs_url = "https://developer.gnome.org/gobject/stable"

  [dependencies."Pango-1.0"]
  name = "Pango"
  description = "Text shaping and rendering"
  docs_url = "https://developer.gnome.org/pango/stable"

  [dependencies."Gdk-3.0"]
  name = "GDK"
  description = "The GTK windowing system abstraction"
  docs_url = "../../Gdk/3.0/"

[theme]
name = "basic"

[source-location]
base_url = "https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/"
